development:
  adapter: postgresql
  database: out_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: out_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: out_production
  pool: 5
  timeout: 5000